[package]
name = "rustyprocdump"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustyprocdump"
path = "src/procdump.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html